### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by atomless** [electerious/scrollSnap#2]
Deprecated in favour of what?

**Comment by electerious** [comment]
In favor of [CSS Scroll Snap Points](https://css-tricks.com/introducing-css-scroll-snap-points/)

**Comment by atomless** [comment]
But css scroll snap has been removed from web standards : https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-destination

**Comment by atomless** [comment]
Your implementation seems superior to the polyfills available for css scroll points. Especially since css scroll points is now removed from web standards. I guess deprecation means you're no longer actively supporting or maintaining it but it also implies there's something better out there and I'm not sure that's the case.
